name: Cow

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: CowSay
        run: |
          sudo docker build -t kyala16/koala-vader .
          sudo docker run kyala16/koala-vader -f vader-koala "Tiiimpphh"
        
